library(plyr)
library(dplyr)
library(shiny)
library(pryr)
library(readxl)
library(readr)
library(shinythemes)
library(leaflet)
library(plotly)
library(tidyverse)
library(DT)
library(data.table)
library(hablar)
library(dplyr)
library(outliers)
library(shinyjs)
library(V8)
library(shinyalert)

jsResetCode <- "shinyjs.reset = function() {history.go(0)}" #To restart the app
Sys.setlocale('LC_ALL','C')